apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: converted-from-terraform
spec:
  schema:
    apiVersion: v1alpha1
    kind: ConvertedFromTerraform
    spec:
      cluster_name: "string | default=\"demo\""
      ingress_rules: "string | default=[{\"cidrs\": [\"10.0.0.0/8\"], \"from_port\": 443, \"to_port\": 443}, {\"cidrs\": [\"10.1.0.0/16\"], \"from_port\": 22, \"to_port\": 22}]"
      k8s_version: "string | default=\"1.31\""
    status:
      cluster_endpoint: "${resources.this.status.atProvider.endpoint}"
  resources:
    - id: this
      template:
        apiVersion: eks.aws.upbound.io/v1beta1
        kind: Cluster
        metadata:
          name: "${schema.spec.cluster_name}"
        spec:
          forProvider:
            name: "${schema.spec.cluster_name}"
            roleArn: "${resources.cluster.status.atProvider.arn}"
            version: "${schema.spec.k8s_version}"
            accessConfig:
              authenticationMode: API
              bootstrapClusterCreatorAdminPermissions: true
            vpcConfig:
              endpointPrivateAccess: true
              endpointPublicAccess: false
              subnetIds:
                - subnet-aaaa
                - subnet-bbbb
    - id: cluster
      template:
        apiVersion: iam.aws.upbound.io/v1beta1
        kind: Role
        metadata:
          name: "${(schema.spec.cluster_name + \"-eks-role\")}"
        spec:
          forProvider:
            assumeRolePolicy: "{\"Statement\":[{\"Action\":\"sts:AssumeRole\",\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"eks.amazonaws.com\"}}],\"Version\":\"2012-10-17\"}"
            name: "${(schema.spec.cluster_name + \"-eks-role\")}"
    - id: cluster_sg
      template:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: SecurityGroup
        metadata:
          name: "${(schema.spec.cluster_name + \"-cluster-sg\")}"
        spec:
          forProvider:
            description: EKS cluster ingress rules
            name: "${(schema.spec.cluster_name + \"-cluster-sg\")}"
            egress:
              cidrBlocks:
                - 0.0.0.0/0
              fromPort: 0
              protocol: -1
              toPort: 0
            ingress: "${schema.spec.ingress_rules.map(item, {\"cidrBlocks\": item.cidrs, \"fromPort\": item.from_port, \"protocol\": \"tcp\", \"toPort\": item.to_port})}"
